SELECT C.NAME, COUNT(P.ID) AS PROJECT_COUNT
FROM CLIENT C
         JOIN PROJECT P ON C.ID = P.CLIENT_ID
GROUP BY C.ID, C.NAME
HAVING COUNT(P.ID) = (
    SELECT MAX(PROJECTS_PER_CLIENT)
    FROM (
             SELECT COUNT(P2.ID) AS PROJECTS_PER_CLIENT
             FROM CLIENT C2
                      JOIN PROJECT P2 ON C2.ID = P2.CLIENT_ID
             GROUP BY C2.ID
         ) AS COUNTS
);
