SELECT P.ID AS PROJECT_ID,
       DATEDIFF('MONTH', P.START_DATE, P.FINISH_DATE) AS DURATION_MONTHS
FROM PROJECT P
WHERE DATEDIFF('MONTH', P.START_DATE, P.FINISH_DATE) = (
    SELECT MAX(DATEDIFF('MONTH', START_DATE, FINISH_DATE))
    FROM PROJECT
    );
