CREATE TABLE IF NOT EXISTS CLIENT
(
    ID   INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (char_length(NAME) BETWEEN 2 AND 1000)
);

CREATE TABLE IF NOT EXISTS WORKER
(
    ID       INT PRIMARY KEY,
    NAME     VARCHAR(1000) NOT NULL CHECK (char_length(NAME) BETWEEN 2 AND 1000),
    BIRTHDAY DATE,
    LEVEL    VARCHAR(20)   NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY   INTEGER       NOT NULL CHECK (SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE IF NOT EXISTS PROJECT
(
    ID          INT PRIMARY KEY,
    CLIENT_ID   INT NOT NULL REFERENCES CLIENT (ID) ON DELETE CASCADE,
    START_DATE  DATE,
    FINISH_DATE DATE
);

CREATE TABLE IF NOT EXISTS PROJECT_WORKER
(
    PROJECT_ID INT NOT NULL REFERENCES PROJECT (ID) ON DELETE CASCADE,
    WORKER_ID  INT NOT NULL REFERENCES WORKER (ID) ON DELETE CASCADE,
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);
