SELECT
    CONCAT('Project ', P.ID) AS PROJECT_NAME,
    (DATEDIFF('MONTH', P.START_DATE, P.FINISH_DATE) * SUM(W.SALARY)) AS PRICE
FROM PROJECT P
         JOIN PROJECT_WORKER PW ON P.ID = PW.PROJECT_ID
         JOIN WORKER W ON PW.WORKER_ID = W.ID
GROUP BY P.ID, P.START_DATE, P.FINISH_DATE
ORDER BY PRICE DESC;